obj-y := dma-buf.o fence.o reservation.o seqno-fence.o fence-array.o
obj-$(CONFIG_SYNC_FILE)		+= sync_file.o
# Use driver at staging/android/sw_sync.c
# obj-$(CONFIG_SW_SYNC)		+= sw_sync.o sync_debug.o
