dtb-$(CONFIG_DTB_EXYNOS7420_ZEROFLTE_EUR) += exynos7420-zeroflte_eur_open_06.dtb
dtb-$(CONFIG_DTB_EXYNOS7420_ZEROLTE_EUR) += exynos7420-zerolte_eur_open_06.dtb
dtb-$(CONFIG_DTB_EXYNOS7420_ZEROFLTE_USA) += exynos7420-zeroflte_usa_05.dtb
dtb-$(CONFIG_DTB_EXYNOS7420_ZEROLTE_USA) += exynos7420-zerolte_usa_05.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
